import type { MovieCard } from "@/features/discovery/schema";

export const curatedCatalog: MovieCard[] = [
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    runtimeMinutes: 164,
    rating: 8,
    genre: "sci-fi",
    mood: "reflective",
    confidence: 0.8,
    freshnessHours: 48,
    synopsis: "A memory-haunted blade runner uncovers a secret that forces him to rewrite what it means to be human.",
    posterUrl: "https://images.unsplash.com/photo-1489599510624-76f5d8f9bba6?auto=format&fit=crop&w=900&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
    reason: "Slow-burn mystery with dense atmosphere and gorgeous production design.",
    source: "curated",
  },
  {
    id: "mad-max-fury-road",
    title: "Mad Max: Fury Road",
    year: 2015,
    runtimeMinutes: 120,
    rating: 8.1,
    genre: "action",
    mood: "adrenaline",
    confidence: 0.88,
    freshnessHours: 24,
    synopsis: "A relentless desert chase turns into a revolution against a violent regime.",
    posterUrl: "https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=900&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1517602302552-471fe67acf66?auto=format&fit=crop&w=1200&q=80",
    reason: "High-intensity kinetic pacing with practical-action spectacle.",
    source: "curated",
  },
  {
    id: "spider-verse",
    title: "Spider-Man: Into the Spider-Verse",
    year: 2018,
    runtimeMinutes: 117,
    rating: 8.4,
    genre: "animation",
    mood: "playful",
    confidence: 0.84,
    freshnessHours: 36,
    synopsis: "Miles Morales discovers multiple Spider-heroes and learns to own his style.",
    posterUrl: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?auto=format&fit=crop&w=900&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1522124624696-7ea32eb9592c?auto=format&fit=crop&w=1200&q=80",
    reason: "Inventive visual language with upbeat momentum and heart.",
    source: "curated",
  },
  {
    id: "arrival",
    title: "Arrival",
    year: 2016,
    runtimeMinutes: 116,
    rating: 7.9,
    genre: "drama",
    mood: "atmospheric",
    confidence: 0.82,
    freshnessHours: 72,
    synopsis: "A linguist races to interpret alien language before global conflict ignites.",
    posterUrl: "https://images.unsplash.com/photo-1505686994434-e3cc5abf1330?auto=format&fit=crop&w=900&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?auto=format&fit=crop&w=1200&q=80",
    reason: "Elegant pace with thoughtful emotional payoff.",
    source: "curated",
  },
  {
    id: "prisoners",
    title: "Prisoners",
    year: 2013,
    runtimeMinutes: 153,
    rating: 8.2,
    genre: "thriller",
    mood: "reflective",
    confidence: 0.8,
    freshnessHours: 52,
    synopsis: "A father's desperate search for his daughter collides with an obsessive detective's case.",
    posterUrl: "https://images.unsplash.com/photo-1542204165-65bf26472b9b?auto=format&fit=crop&w=900&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1520828744485-1a6f64f6abde?auto=format&fit=crop&w=1200&q=80",
    reason: "Morally tense thriller with layered performances and suspense.",
    source: "curated",
  },
];
